[build]
builder = "nixpacks"

[deploy]
startCommand = "python api.py"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[env]
LOG_LEVEL = "INFO"
LOG_FORMAT = "json"
PYTHONUNBUFFERED = "1"